/* eslint-disable import/prefer-default-export */
export const TEAM_ACTION_TYPES = {
  FETCH_TEAMS_START: 'team/FETCH_TEAMS_START',
  FETCH_TEAMS_SUCCESS: 'team/FETCH_TEAMS_SUCCESS',
  FETCH_TEAMS_FAILURE: 'team/FETCH_TEAMS_FAILURE',
  SET_TEAM_PLAYERS_START: 'team/SET_TEAM_PLAYERS_START',
  SET_TEAM_PLAYERS_SUCCESS: 'team/SET_TEAM_PLAYERS_SUCCESS',
  SET_TEAM_PLAYERS_FAILURE: 'team/SET_TEAM_PLAYERS_FAILURE',
  SET_SELECTED_TEAM: 'team/SET_SELECTED_TEAM',
  SET_FILTERED_PLAYERS: 'team/SET_FILTERED_PLAYERS',
  SET_SEASON: 'team/SET_SEASON',
};
